### ISSUE TITLE
does not understand about docker-compose file

### ISSUE THREAD

**Issue by swdream** [siyangbi/docker-nginx-node-postgres-elasticsearch#11]
hello, sorry for a stupid question.
in your docker-compose file:
```
volumes:
  mysql:
    driver: "local"
  elasticsearch:
    driver: "local"
  redis:
    driver: "local"
```
I don't understand about it. Could you please help me to explain what it does. speacial thanks
